### ISSUE TITLE
HOW to pull docker image?

### ISSUE THREAD

**Issue by Ruk1ng001** [T-Systems-MMS/hyperledger-avalon-scone#1]
when I run:
```bash
docker-compose -f docker-compose-scone-sim.yaml up --build
```
get:
```bash
Step 1/35 : FROM registry.scontain.com:5050/sconecuratedimages/muslgcc as libraries
latest: Pulling from sconecuratedimages/muslgcc
85aff17ac923: Downloading [=>                                                 ]  3.715MB/184.1MB
```
The speed is so low...

**Comment by mujtabaidrees94** [comment]
Hi @Ren-HK , 

In order to run the demos the access to SCONE images is required. SCONE uses gitlab as their docker images directory.

1. Register at https://gitlab.scontain.com and then request access for SCONE images in community version.
2. Login using gitlab credentials `docker login registry.scontain.com:5050`
3. After successful login you can access the SCONE images required for Hyperledger Avalon and test the workflows.

I have also updated the prerequisites page. 
https://github.com/T-Systems-MMS/hyperledger-avalon-scone/blob/main/PREREQUISITES.md#scone

**Comment by Ruk1ng001** [comment]
```bash
root@u18:/home/u18/workspace/hyperledger-avalon-scone# docker login registry.scontain.com:5050 -u scone -p 6ybsypgfxiFp45viD-M3
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
root@u18:/home/u18/workspace/hyperledger-avalon-scone# docker pull sconecuratedimages/crosscompilers:alpine
Error response from daemon: pull access denied for sconecuratedimages/crosscompilers, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
root@u18:/home/u18/workspace/hyperledger-avalon-scone# 
```
I login Succeeded, but also cant pull image.
I don't how to get the access the authority.
![image](https://user-images.githubusercontent.com/57079399/106875751-fd7f1080-6711-11eb-9070-af0dff4c1249.png)
![image](https://user-images.githubusercontent.com/57079399/106876042-4636c980-6712-11eb-8ea5-905b66923fbb.png)

**Comment by mujtabaidrees94** [comment]
1. You can pull images like this 
`docker pull registry.scontain.com:5050/sconecuratedimages/muslgcc:alpine-scone5`

2. However, I am told by scontain team that CAS and LAS images are not available in the free tier. I am trying to work it out with them. 

3. In the meanwhile please try to run the demos from **no-cas-fs-unprotected** branch, as they do not use SCONE CAS/LAS.
Follow the guidelines here
`https://github.com/T-Systems-MMS/hyperledger-avalon-scone/blob/no-cas-fs-unprotected/avalon-scone/README.md#building-and-running-the-workers-for-testing-1-without-sconeintel-sgx-2-scone-sim-mode-3-unsecure-hardware-mode`

**Comment by Ruk1ng001** [comment]
I cant pull this image :
```bash
FROM sconecuratedimages/crosscompilers:runtime-alpine3.7-scone4
ERROR: Service 'scone-worker-4' failed to build: pull access denied for sconecuratedimages/crosscompilers, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Can I get the permission of crosscompilers?This is private .
![image](https://user-images.githubusercontent.com/57079399/106981141-6e6b0a80-679c-11eb-9fd6-927369483cd5.png)

**Comment by mujtabaidrees94** [comment]
Hi, 

I shifted the docker images to the Scontain's gitlab registry after your first comment. Have you pulled latest code? Please do git pull and then try again. 
It should be
`FROM registry.scontain.com:5050/sconecuratedimages/crosscompilers:runtime-alpine3.7-scone4`

Or if I missed it, please point me to the file name.

**Comment by mujtabaidrees94** [comment]
@Ren-HK I have also provided the integration with SCONE's public CAS so that secure mode can be run in free tier. Please get latest the 'main' branch and feel free to explore it. I have marked it stable too.

**Comment by AnanKing** [comment]
I login successfully, but also cannot pull the image.
I don't know how to get access to the authority.

When I run the command:
`docker pull registry.scontain.com:5050/sconecuratedimages/helloworld`
The result show that:
`Error response from daemon: pull access denied for registry.scontain.com:5050/sconecuratedimages/helloworld, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

How to fix it?

Who can help me?

**Comment by mujtabaidrees94** [comment]
Here are instructions on accessing scontain registry:
https://sconedocs.github.io/registry/
